---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-aurora
# description will be included in the image's metadata
description: Aurora-based image with maccel mouse acceleration support

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      files:
        - https://raw.githubusercontent.com/abirkel/maccel-rpm/main/maccel.repo
    install:
      packages:
        - akmods
        - kernel-devel
        - akmod-maccel

  # Build the kernel module during image creation
  - type: script
    scripts:
      - |
        #!/usr/bin/bash
        set -euo pipefail
        
        echo "Building maccel kernel module..."
        
        ARCH="$(rpm -E '%_arch')"
        KERNEL="$(rpm -q kernel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')"
        
        # Build the kernel module for the current kernel
        akmods --force --kernels "${KERNEL}" --kmod maccel
        
        # Verify the module was built successfully
        if modinfo "/usr/lib/modules/${KERNEL}/extra/maccel/maccel.ko.xz" > /dev/null 2>&1; then
          echo "✓ maccel kernel module built successfully for kernel ${KERNEL}"
        else
          echo "✗ Failed to build maccel kernel module"
          find /var/cache/akmods/maccel/ -name "*.log" -exec cat {} \;
          exit 1
        fi

  - type: signing  # Sets up policy & signing files for signed images
